<definition>
	<command name="assertClick">
		<case locator-key1="ENTRIES_DOCUMENT_SEARCH_TITLE">
			<execute function="AssertClick#assertTextClickAtAndWait" />
		</case>
	</command>

	<command name="Click">
		<case locator-key1="TOOLBAR_DISPLAY_DESCRIPTIVE">
			<execute function="Click#clickAtAndWait" />
		</case>
		<case locator-key1="TOOLBAR_DISPLAY_ICON">
			<execute function="Click#clickAtAndWait" />
		</case>
		<case locator-key1="TOOLBAR_DISPLAY_LIST">
			<execute function="Click#clickAtAndWait" />
		</case>
	</command>
</definition>